global:
  scrape_interval: 5s  # Adjust as needed

scrape_configs:
  # Scraping Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape metrics from the Node.js server
  - job_name: 'nodejs-server'
    static_configs:
      - targets: ['server:5000']  # Ensure your server exposes metrics at /metrics

  # Scrape Loki logs (optional for Promtail logs)
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']